name:                hdns
version:             0.1.0.0
github:              "owainlewis/hdns"
license:             BSD3
author:              "Owain Lewis"
maintainer:          "owain@owainlewis.com"
copyright:           "2019 Owain Lewis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/owainlewis/hdns#readme>

dependencies:
- base >= 4.7 && < 5
- network
- dns
- bytestring

library:
  source-dirs: src

executables:
  hdns-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hdns

tests:
  hdns-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hdns
